import type {
  ActiveWorkout,
  CoachData,
  DashboardDay,
  Exercise,
  HistorySession,
  ProgressData,
  RecoveryData,
} from "./types";

/** Deterministic mock data. Replace with Lovable Cloud queries later. */

const hrSeries = (() => {
  const pts: { t: string; hr: number }[] = [];
  // 06:40 -> 07:52 cardio block, then evening lifting block
  const shape = [
    82, 96, 118, 132, 141, 147, 152, 156, 161, 158, 149, 155, 164, 171, 168, 159, 151, 146, 138,
    129, 118, 104, 96, 91, 88, 92, 104, 116, 124, 131, 127, 119, 133, 142, 138, 126, 115, 108, 101,
    95,
  ];
  shape.forEach((hr, i) => {
    const total = 6 * 60 + 40 + i * 12;
    const h = Math.floor(total / 60) % 24;
    const m = total % 60;
    pts.push({ t: `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}`, hr });
  });
  return pts;
})();

export const dashboardDay: DashboardDay = {
  date: "Wednesday, 26 August",
  statusLine: "On target",
  ironScore: 84,
  grade: "A-",
  strain: {
    total: 14.6,
    cardioPercent: 42,
    muscularPercent: 58,
    interpretation:
      "Strong mixed-modal day. Muscular strain leads on a lower-body focus, cardio load stays inside your aerobic band. Recovery cost is manageable.",
  },
  sessions: [
    {
      id: "s1",
      name: "Zone 2 Tempo Run",
      kind: "cardio",
      startedAt: "06:40",
      durationMin: 48,
      calories: 512,
      avgHr: 148,
      maxHr: 171,
      cardioLoad: 96,
      activeZoneMinutes: 41,
      zones: [
        { zone: "light", minutes: 9, percent: 19 },
        { zone: "moderate", minutes: 24, percent: 50 },
        { zone: "vigorous", minutes: 12, percent: 25 },
        { zone: "peak", minutes: 3, percent: 6 },
      ],
      notes: "Held cadence 172. Negative split final 10 minutes.",
    },
    {
      id: "s2",
      name: "Lower Body — Squat Focus",
      kind: "strength",
      startedAt: "18:05",
      durationMin: 62,
      calories: 438,
      avgHr: 121,
      maxHr: 142,
      cardioLoad: 44,
      activeZoneMinutes: 18,
      zones: [
        { zone: "light", minutes: 31, percent: 50 },
        { zone: "moderate", minutes: 22, percent: 35 },
        { zone: "vigorous", minutes: 8, percent: 13 },
        { zone: "peak", minutes: 1, percent: 2 },
      ],
      notes: "Back squat triple at 150 kg felt controlled. RPE 8.",
    },
  ],
  hrSeries,
  avgHr: 129,
  zoneTotals: [
    { zone: "light", minutes: 40, percent: 36 },
    { zone: "moderate", minutes: 46, percent: 42 },
    { zone: "vigorous", minutes: 20, percent: 18 },
    { zone: "peak", minutes: 4, percent: 4 },
  ],
  strength: {
    totalSets: 23,
    totalReps: 164,
    tonnageKg: 14820,
    topLift: { exercise: "Back Squat", weightKg: 150, reps: 3 },
    e1rmDeltaKg: 3.5,
    prs: [
      { exercise: "Back Squat", detail: "Est. 1RM 165 kg (+3.5 kg)" },
      { exercise: "Romanian Deadlift", detail: "8 reps @ 130 kg — rep PR" },
    ],
  },
  nutrition: {
    targets: { calories: 2900, proteinG: 190, carbsG: 330, fatG: 85 },
    consumed: { calories: 2614, proteinG: 176, carbsG: 291, fatG: 74 },
    meals: [
      {
        id: "m1",
        name: "Breakfast",
        time: "08:10",
        calories: 620,
        proteinG: 42,
        carbsG: 68,
        fatG: 18,
        items: ["Oats + whey", "Blueberries", "Black coffee"],
      },
      {
        id: "m2",
        name: "Lunch",
        time: "12:45",
        calories: 780,
        proteinG: 55,
        carbsG: 82,
        fatG: 22,
        items: ["Chicken rice bowl", "Avocado", "Kimchi"],
      },
      {
        id: "m3",
        name: "Pre-session",
        time: "17:15",
        calories: 310,
        proteinG: 20,
        carbsG: 52,
        fatG: 4,
        items: ["Rice cakes", "Greek yoghurt"],
      },
      {
        id: "m4",
        name: "Dinner",
        time: "20:05",
        calories: 904,
        proteinG: 59,
        carbsG: 89,
        fatG: 30,
        items: ["Sirloin", "Potatoes", "Greens"],
      },
    ],
    hydrationMl: 2900,
    hydrationTargetMl: 3800,
    weightGoal: { direction: "maintain", rateKgPerWeek: 0 },
  },
  energy: {
    intake: 2614,
    bmr: 1810,
    exerciseBurn: 950,
    net: -146,
    status: "deficit",
  },
  grades: [
    { label: "Cardio", grade: "A", score: 91, note: "Aerobic base session executed as prescribed" },
    { label: "Strength", grade: "A-", score: 88, note: "Tonnage above 4-week average" },
    { label: "Nutrition", grade: "B+", score: 82, note: "Protein 14 g short of target" },
    { label: "Recovery", grade: "B", score: 76, note: "Sleep 6h 42m — below 7h 30m floor" },
    { label: "Consistency", grade: "A", score: 94, note: "6 of last 7 days on plan" },
    { label: "Overall", grade: "A-", score: 84, note: "High output, recovery is the limiter" },
  ],
  suggestions: [
    {
      id: "g1",
      title: "Close the protein gap tonight",
      detail:
        "Add 25 g casein or Greek yoghurt before bed to hit 190 g and support squat recovery.",
      severity: "warn",
    },
    {
      id: "g2",
      title: "Protect sleep window",
      detail: "Lights out by 22:45. Two consecutive sub-7h nights would drop readiness below 65.",
      severity: "risk",
    },
    {
      id: "g3",
      title: "Finish hydration",
      detail: "900 ml behind target. Add electrolytes after the morning run tomorrow.",
      severity: "info",
    },
    {
      id: "g4",
      title: "Keep tomorrow aerobic",
      detail: "Acute load is 18% above chronic. Cap tomorrow at zone 2 for 40 minutes.",
      severity: "warn",
    },
    {
      id: "g5",
      title: "Bank the squat progress",
      detail: "Repeat 150 kg for 3×3 next session before adding load — velocity was stable.",
      severity: "good",
    },
  ],
  keyTakeaway:
    "You earned a high-output day without overreaching: cardio stayed aerobic and squat velocity held at a new estimated 1RM. Recovery is now the constraint — sleep and protein tonight decide whether this becomes adaptation or accumulated fatigue.",
  weeklyLoad: [
    { day: "Thu", load: 62 },
    { day: "Fri", load: 88 },
    { day: "Sat", load: 34 },
    { day: "Sun", load: 105 },
    { day: "Mon", load: 71 },
    { day: "Tue", load: 24 },
    { day: "Wed", load: 140 },
  ],
  recentProgress: [
    { label: "Squat e1RM", value: "165 kg", delta: "+3.5 kg", positive: true },
    { label: "Weekly tonnage", value: "58,400 kg", delta: "+6%", positive: true },
    { label: "Resting HR", value: "48 bpm", delta: "-2 bpm", positive: true },
    { label: "Sleep avg", value: "6h 58m", delta: "-18 min", positive: false },
  ],
};

export const activeWorkout: ActiveWorkout = {
  id: "w-active",
  title: "Upper Body — Press Focus",
  focus: "Chest · Shoulders · Triceps",
  startedAt: "18:02",
  elapsedSec: 1462,
  notes: "Right shoulder slightly tight on first warm-up set. Stayed on bar path drills.",
  exercises: [
    {
      id: "e1",
      name: "Barbell Bench Press",
      muscle: "Chest",
      equipment: "Barbell",
      targetSets: 4,
      targetReps: "5",
      previous: "4×5 @ 102.5 kg · RPE 8",
      sets: [
        { id: "e1s1", weightKg: 105, reps: 5, rpe: 7.5, done: true },
        { id: "e1s2", weightKg: 105, reps: 5, rpe: 8, done: true },
        { id: "e1s3", weightKg: 105, reps: 4, rpe: 9, done: true },
        { id: "e1s4", weightKg: 105, reps: 0, rpe: 8, done: false },
      ],
    },
    {
      id: "e2",
      name: "Seated Dumbbell Shoulder Press",
      muscle: "Shoulders",
      equipment: "Dumbbell",
      targetSets: 3,
      targetReps: "8-10",
      previous: "3×9 @ 32 kg · RPE 8",
      sets: [
        { id: "e2s1", weightKg: 32, reps: 10, rpe: 7, done: true },
        { id: "e2s2", weightKg: 32, reps: 9, rpe: 8, done: true },
        { id: "e2s3", weightKg: 32, reps: 0, rpe: 8, done: false },
      ],
    },
    {
      id: "e3",
      name: "Weighted Dip",
      muscle: "Triceps",
      equipment: "Bodyweight + belt",
      targetSets: 3,
      targetReps: "6-8",
      previous: "3×7 @ +25 kg · RPE 8",
      sets: [
        { id: "e3s1", weightKg: 25, reps: 0, rpe: 8, done: false },
        { id: "e3s2", weightKg: 25, reps: 0, rpe: 8, done: false },
        { id: "e3s3", weightKg: 25, reps: 0, rpe: 8, done: false },
      ],
    },
    {
      id: "e4",
      name: "Cable Lateral Raise",
      muscle: "Shoulders",
      equipment: "Cable",
      targetSets: 3,
      targetReps: "12-15",
      previous: "3×14 @ 12.5 kg · RPE 9",
      sets: [
        { id: "e4s1", weightKg: 12.5, reps: 0, rpe: 9, done: false },
        { id: "e4s2", weightKg: 12.5, reps: 0, rpe: 9, done: false },
        { id: "e4s3", weightKg: 12.5, reps: 0, rpe: 9, done: false },
      ],
    },
  ],
};

export const historySessions: HistorySession[] = [
  {
    id: "h1",
    date: "2026-08-26",
    title: "Lower Body — Squat Focus",
    kind: "strength",
    bodyParts: ["Quads", "Glutes", "Hamstrings"],
    durationMin: 62,
    tonnageKg: 14820,
    sets: 23,
    reps: 164,
    avgRpe: 8.1,
    intensity: "hard",
    calories: 438,
    prCount: 2,
    blocks: [
      { exercise: "Back Squat", detail: "5×3 @ 150 kg" },
      { exercise: "Romanian Deadlift", detail: "4×8 @ 130 kg" },
      { exercise: "Leg Press", detail: "3×12 @ 220 kg" },
      { exercise: "Standing Calf Raise", detail: "4×15 @ 90 kg" },
    ],
  },
  {
    id: "h2",
    date: "2026-08-26",
    title: "Zone 2 Tempo Run",
    kind: "cardio",
    bodyParts: ["Full body"],
    durationMin: 48,
    tonnageKg: 0,
    sets: 0,
    reps: 0,
    avgRpe: 6.4,
    intensity: "moderate",
    calories: 512,
    prCount: 0,
    blocks: [{ exercise: "Tempo run", detail: "9.6 km · 4:58/km · avg HR 148" }],
  },
  {
    id: "h3",
    date: "2026-08-25",
    title: "Upper Body — Pull",
    kind: "strength",
    bodyParts: ["Back", "Biceps"],
    durationMin: 54,
    tonnageKg: 11240,
    sets: 20,
    reps: 152,
    avgRpe: 7.6,
    intensity: "moderate",
    calories: 372,
    prCount: 1,
    blocks: [
      { exercise: "Weighted Pull-up", detail: "5×5 @ +20 kg" },
      { exercise: "Barbell Row", detail: "4×8 @ 100 kg" },
      { exercise: "Chest-Supported Row", detail: "3×12 @ 60 kg" },
    ],
  },
  {
    id: "h4",
    date: "2026-08-24",
    title: "Conditioning — Rower Intervals",
    kind: "conditioning",
    bodyParts: ["Full body"],
    durationMin: 32,
    tonnageKg: 0,
    sets: 8,
    reps: 0,
    avgRpe: 8.8,
    intensity: "peak",
    calories: 418,
    prCount: 0,
    blocks: [{ exercise: "Row 8×500 m", detail: "1:42 avg · 90s rest" }],
  },
  {
    id: "h5",
    date: "2026-08-23",
    title: "Mobility & Core",
    kind: "mobility",
    bodyParts: ["Core", "Hips"],
    durationMin: 28,
    tonnageKg: 1200,
    sets: 12,
    reps: 148,
    avgRpe: 4.2,
    intensity: "light",
    calories: 138,
    prCount: 0,
    blocks: [
      { exercise: "Copenhagen plank", detail: "3×30s/side" },
      { exercise: "Hip flow", detail: "12 min" },
    ],
  },
  {
    id: "h6",
    date: "2026-08-22",
    title: "Full Body — Deadlift Focus",
    kind: "strength",
    bodyParts: ["Back", "Hamstrings", "Glutes"],
    durationMin: 68,
    tonnageKg: 16340,
    sets: 22,
    reps: 138,
    avgRpe: 8.6,
    intensity: "peak",
    calories: 486,
    prCount: 1,
    blocks: [
      { exercise: "Deadlift", detail: "5×3 @ 185 kg" },
      { exercise: "Front Squat", detail: "4×6 @ 110 kg" },
      { exercise: "Hanging Leg Raise", detail: "3×12" },
    ],
  },
  {
    id: "h7",
    date: "2026-08-21",
    title: "Easy Aerobic Bike",
    kind: "cardio",
    bodyParts: ["Legs"],
    durationMin: 45,
    tonnageKg: 0,
    sets: 0,
    reps: 0,
    avgRpe: 4.8,
    intensity: "light",
    calories: 344,
    prCount: 0,
    blocks: [{ exercise: "Bike", detail: "45 min · avg HR 122" }],
  },
];

const trend = (base: number, steps: number[]) =>
  steps.map((s, i) => ({
    date: `W${i + 1}`,
    e1rm: base + s,
  }));

/**
 * The signed-in database ships a broad system library. Demo mode should expose
 * the same kind of choice instead of making the builder look like a ten-item
 * prototype, so these lightweight rows fill out the searchable preview catalog.
 */
const demoExerciseLibraryExtras: Exercise[] = (
  [
    ["Goblet Squat", "Quads", ["Glutes", "Core"], "Kettlebell", "Squat"],
    ["Bulgarian Split Squat", "Quads", ["Glutes", "Adductors"], "Dumbbell", "Lunge"],
    ["Walking Lunge", "Quads", ["Glutes", "Hamstrings"], "Dumbbell", "Lunge"],
    ["Step-Up", "Quads", ["Glutes"], "Dumbbell", "Lunge"],
    ["Conventional Deadlift", "Hamstrings", ["Glutes", "Upper Back", "Core"], "Barbell", "Hinge"],
    ["Trap Bar Deadlift", "Hamstrings", ["Glutes", "Quads"], "Trap Bar", "Hinge"],
    ["Hip Thrust", "Glutes", ["Hamstrings"], "Barbell", "Hinge"],
    ["Kettlebell Swing", "Glutes", ["Hamstrings", "Core"], "Kettlebell", "Hinge"],
    ["Back Extension", "Lower Back", ["Glutes", "Hamstrings"], "Bodyweight", "Hinge"],
    ["Leg Curl", "Hamstrings", ["Calves"], "Machine", "Isolation"],
    ["Leg Extension", "Quads", [], "Machine", "Isolation"],
    ["Standing Calf Raise", "Calves", [], "Machine", "Isolation"],
    ["Incline Bench Press", "Chest", ["Front Delts", "Triceps"], "Barbell", "Horizontal Push"],
    ["Dumbbell Bench Press", "Chest", ["Triceps"], "Dumbbell", "Horizontal Push"],
    ["Machine Chest Press", "Chest", ["Triceps"], "Machine", "Horizontal Push"],
    ["Push-Up", "Chest", ["Triceps", "Core"], "Bodyweight", "Horizontal Push"],
    ["Cable Fly", "Chest", [], "Cable", "Isolation"],
    ["Seated Dumbbell Press", "Shoulders", ["Triceps"], "Dumbbell", "Vertical Push"],
    ["Lateral Raise", "Shoulders", [], "Dumbbell", "Isolation"],
    ["Rear Delt Fly", "Shoulders", ["Upper Back"], "Dumbbell", "Isolation"],
    ["Dip", "Triceps", ["Chest", "Shoulders"], "Dip Station", "Vertical Push"],
    ["Pull-Up", "Lats", ["Biceps", "Upper Back"], "Pull-Up Bar", "Vertical Pull"],
    ["Chin-Up", "Lats", ["Biceps"], "Pull-Up Bar", "Vertical Pull"],
    ["Lat Pulldown", "Lats", ["Biceps"], "Cable", "Vertical Pull"],
    ["Dumbbell Row", "Upper Back", ["Lats", "Biceps"], "Dumbbell", "Horizontal Pull"],
    ["Seated Cable Row", "Upper Back", ["Lats", "Biceps"], "Cable", "Horizontal Pull"],
    ["Face Pull", "Upper Back", ["Shoulders"], "Cable", "Horizontal Pull"],
    ["Barbell Curl", "Biceps", ["Forearms"], "Barbell", "Isolation"],
    ["Incline Dumbbell Curl", "Biceps", [], "Dumbbell", "Isolation"],
    ["Triceps Pushdown", "Triceps", [], "Cable", "Isolation"],
    ["Skullcrusher", "Triceps", [], "EZ Bar", "Isolation"],
    ["Plank", "Core", ["Shoulders"], "Bodyweight", "Core"],
    ["Cable Crunch", "Core", [], "Cable", "Core"],
    ["Pallof Press", "Core", ["Obliques"], "Cable", "Core"],
    ["Farmer Carry", "Core", ["Traps", "Forearms"], "Dumbbell", "Carry"],
    ["Sled Push", "Quads", ["Glutes", "Calves"], "Sled", "Conditioning"],
    ["Air Bike Intervals", "Full Body", ["Legs"], "Air Bike", "Conditioning"],
    ["Treadmill Zone 2", "Full Body", ["Legs"], "Treadmill", "Conditioning"],
    ["Jump Rope", "Calves", ["Shoulders"], "Jump Rope", "Conditioning"],
  ] as const
).map(([name, muscle, secondary, equipment, pattern]) => ({
  id: `demo-${name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")}`,
  name,
  muscle,
  secondary: [...secondary],
  equipment,
  pattern,
  favorite: false,
  best: { weightKg: 0, reps: 0 },
  e1rmTrend: [],
  history: [],
  cues: [],
}));

export const exercises: Exercise[] = [
  {
    id: "back-squat",
    name: "Back Squat",
    muscle: "Quads",
    secondary: ["Glutes", "Core"],
    equipment: "Barbell",
    pattern: "Squat",
    favorite: true,
    lastPerformed: "2026-08-26",
    best: { weightKg: 150, reps: 3 },
    e1rmTrend: trend(150, [0, 2, 3, 5, 8, 11, 15]),
    history: [
      { date: "2026-08-26", detail: "5×3 @ 150 kg · RPE 8", tonnageKg: 2250 },
      { date: "2026-08-19", detail: "5×3 @ 147.5 kg · RPE 8", tonnageKg: 2212 },
      { date: "2026-08-12", detail: "4×4 @ 140 kg · RPE 7.5", tonnageKg: 2240 },
    ],
    cues: ["Brace before unracking", "Knees track over mid-foot", "Drive hips and chest together"],
  },
  {
    id: "deadlift",
    name: "Deadlift",
    muscle: "Hamstrings",
    secondary: ["Back", "Glutes"],
    equipment: "Barbell",
    pattern: "Hinge",
    favorite: true,
    lastPerformed: "2026-08-22",
    best: { weightKg: 185, reps: 3 },
    e1rmTrend: trend(190, [0, 1, 4, 4, 7, 9, 12]),
    history: [
      { date: "2026-08-22", detail: "5×3 @ 185 kg · RPE 8.5", tonnageKg: 2775 },
      { date: "2026-08-15", detail: "4×4 @ 175 kg · RPE 8", tonnageKg: 2800 },
    ],
    cues: ["Bar over mid-foot", "Wedge into the floor", "Lock ribs down"],
  },
  {
    id: "bench-press",
    name: "Barbell Bench Press",
    muscle: "Chest",
    secondary: ["Triceps", "Shoulders"],
    equipment: "Barbell",
    pattern: "Horizontal press",
    favorite: true,
    lastPerformed: "2026-08-25",
    best: { weightKg: 105, reps: 5 },
    e1rmTrend: trend(112, [0, 1, 2, 2, 4, 6, 7]),
    history: [
      { date: "2026-08-25", detail: "4×5 @ 105 kg · RPE 8", tonnageKg: 2100 },
      { date: "2026-08-18", detail: "4×5 @ 102.5 kg · RPE 8", tonnageKg: 2050 },
    ],
    cues: ["Shoulder blades down and back", "Elbows 45°", "Leg drive into the bench"],
  },
  {
    id: "weighted-pullup",
    name: "Weighted Pull-up",
    muscle: "Back",
    secondary: ["Biceps"],
    equipment: "Bodyweight + belt",
    pattern: "Vertical pull",
    favorite: false,
    lastPerformed: "2026-08-25",
    best: { weightKg: 20, reps: 5 },
    e1rmTrend: trend(24, [0, 0, 1, 2, 3, 3, 5]),
    history: [{ date: "2026-08-25", detail: "5×5 @ +20 kg · RPE 8", tonnageKg: 500 }],
    cues: ["Full hang start", "Chest to bar", "Control the eccentric"],
  },
  {
    id: "ohp",
    name: "Standing Overhead Press",
    muscle: "Shoulders",
    secondary: ["Triceps", "Core"],
    equipment: "Barbell",
    pattern: "Vertical press",
    favorite: false,
    lastPerformed: "2026-08-18",
    best: { weightKg: 70, reps: 5 },
    e1rmTrend: trend(76, [0, 1, 1, 3, 3, 4, 5]),
    history: [{ date: "2026-08-18", detail: "4×5 @ 70 kg · RPE 8.5", tonnageKg: 1400 }],
    cues: ["Ribs stacked over pelvis", "Head through at lockout"],
  },
  {
    id: "rdl",
    name: "Romanian Deadlift",
    muscle: "Hamstrings",
    secondary: ["Glutes", "Back"],
    equipment: "Barbell",
    pattern: "Hinge",
    favorite: true,
    lastPerformed: "2026-08-26",
    best: { weightKg: 130, reps: 8 },
    e1rmTrend: trend(150, [0, 2, 3, 5, 6, 8, 10]),
    history: [{ date: "2026-08-26", detail: "4×8 @ 130 kg · RPE 8", tonnageKg: 4160 }],
    cues: ["Push hips back", "Bar hugs the thigh", "Stop at stretch, not the floor"],
  },
  {
    id: "barbell-row",
    name: "Barbell Row",
    muscle: "Back",
    secondary: ["Biceps"],
    equipment: "Barbell",
    pattern: "Horizontal pull",
    favorite: false,
    lastPerformed: "2026-08-25",
    best: { weightKg: 100, reps: 8 },
    e1rmTrend: trend(118, [0, 1, 2, 4, 5, 5, 7]),
    history: [{ date: "2026-08-25", detail: "4×8 @ 100 kg · RPE 7.5", tonnageKg: 3200 }],
    cues: ["Torso 45°", "Pull to lower ribs"],
  },
  {
    id: "leg-press",
    name: "Leg Press",
    muscle: "Quads",
    secondary: ["Glutes"],
    equipment: "Machine",
    pattern: "Squat",
    favorite: false,
    lastPerformed: "2026-08-26",
    best: { weightKg: 220, reps: 12 },
    e1rmTrend: trend(260, [0, 4, 6, 8, 12, 14, 18]),
    history: [{ date: "2026-08-26", detail: "3×12 @ 220 kg · RPE 8", tonnageKg: 7920 }],
    cues: ["Full range without lumbar rounding"],
  },
  {
    id: "cable-lateral",
    name: "Cable Lateral Raise",
    muscle: "Shoulders",
    secondary: [],
    equipment: "Cable",
    pattern: "Isolation",
    favorite: false,
    lastPerformed: "2026-08-25",
    best: { weightKg: 12.5, reps: 14 },
    e1rmTrend: trend(16, [0, 0, 1, 1, 2, 2, 3]),
    history: [{ date: "2026-08-25", detail: "3×14 @ 12.5 kg · RPE 9", tonnageKg: 525 }],
    cues: ["Lead with the elbow", "No trap shrug"],
  },
  {
    id: "row-erg",
    name: "Rowing Machine Intervals",
    muscle: "Full body",
    secondary: ["Back", "Legs"],
    equipment: "Erg",
    pattern: "Conditioning",
    favorite: false,
    lastPerformed: "2026-08-24",
    best: { weightKg: 0, reps: 0 },
    e1rmTrend: trend(0, [0, 0, 0, 0, 0, 0, 0]),
    history: [{ date: "2026-08-24", detail: "8×500 m · 1:42 avg", tonnageKg: 0 }],
    cues: ["Legs, back, arms — reverse on return"],
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    muscle: "Core",
    secondary: ["Hips"],
    equipment: "Bodyweight",
    pattern: "Isolation",
    favorite: false,
    lastPerformed: "2026-08-22",
    best: { weightKg: 0, reps: 14 },
    e1rmTrend: trend(0, [0, 0, 0, 0, 0, 0, 0]),
    history: [{ date: "2026-08-22", detail: "3×12 · RPE 8", tonnageKg: 0 }],
    cues: ["Posterior pelvic tilt at the top"],
  },
  {
    id: "front-squat",
    name: "Front Squat",
    muscle: "Quads",
    secondary: ["Core"],
    equipment: "Barbell",
    pattern: "Squat",
    favorite: false,
    lastPerformed: "2026-08-22",
    best: { weightKg: 110, reps: 6 },
    e1rmTrend: trend(128, [0, 1, 3, 3, 5, 6, 8]),
    history: [{ date: "2026-08-22", detail: "4×6 @ 110 kg · RPE 8", tonnageKg: 2640 }],
    cues: ["Elbows high", "Vertical torso"],
  },
  ...demoExerciseLibraryExtras,
];

export const progressData: ProgressData = {
  bodyweight: [
    { date: "Jul 01", kg: 87.4 },
    { date: "Jul 08", kg: 87.1 },
    { date: "Jul 15", kg: 86.6 },
    { date: "Jul 22", kg: 86.8 },
    { date: "Jul 29", kg: 86.2 },
    { date: "Aug 05", kg: 85.9 },
    { date: "Aug 12", kg: 85.6 },
    { date: "Aug 19", kg: 85.8 },
    { date: "Aug 26", kg: 85.2 },
  ],
  e1rm: [
    { date: "Jul 01", squat: 150, bench: 112, deadlift: 190 },
    { date: "Jul 08", squat: 152, bench: 112, deadlift: 191 },
    { date: "Jul 15", squat: 153, bench: 114, deadlift: 194 },
    { date: "Jul 22", squat: 155, bench: 114, deadlift: 194 },
    { date: "Jul 29", squat: 158, bench: 116, deadlift: 197 },
    { date: "Aug 05", squat: 161, bench: 118, deadlift: 199 },
    { date: "Aug 12", squat: 162, bench: 118, deadlift: 200 },
    { date: "Aug 19", squat: 163, bench: 119, deadlift: 202 },
    { date: "Aug 26", squat: 165, bench: 119, deadlift: 202 },
  ],
  volume: [
    { week: "W-8", tonnage: 44_200 },
    { week: "W-7", tonnage: 47_800 },
    { week: "W-6", tonnage: 51_100 },
    { week: "W-5", tonnage: 38_400 },
    { week: "W-4", tonnage: 52_600 },
    { week: "W-3", tonnage: 54_900 },
    { week: "W-2", tonnage: 55_100 },
    { week: "W-1", tonnage: 58_400 },
  ],
  load: [
    { week: "W-8", acute: 380, chronic: 402 },
    { week: "W-7", acute: 402, chronic: 405 },
    { week: "W-6", acute: 438, chronic: 412 },
    { week: "W-5", acute: 320, chronic: 405 },
    { week: "W-4", acute: 446, chronic: 410 },
    { week: "W-3", acute: 468, chronic: 421 },
    { week: "W-2", acute: 472, chronic: 435 },
    { week: "W-1", acute: 512, chronic: 442 },
  ],
  cardioFitness: [
    { date: "Jul 01", vo2: 48.1 },
    { date: "Jul 15", vo2: 48.9 },
    { date: "Jul 29", vo2: 49.6 },
    { date: "Aug 12", vo2: 50.4 },
    { date: "Aug 26", vo2: 51.2 },
  ],
  streak: { currentWeeks: 23, bestWeeks: 41, weeksTracked: 7 },
  prs: [
    { date: "2026-08-26", exercise: "Back Squat", detail: "Est. 1RM 165 kg (+3.5 kg)" },
    { date: "2026-08-26", exercise: "Romanian Deadlift", detail: "8 reps @ 130 kg" },
    { date: "2026-08-25", exercise: "Weighted Pull-up", detail: "5 reps @ +20 kg" },
    { date: "2026-08-22", exercise: "Deadlift", detail: "3 reps @ 185 kg" },
    { date: "2026-08-18", exercise: "Overhead Press", detail: "5 reps @ 70 kg" },
    { date: "2026-08-12", exercise: "Front Squat", detail: "6 reps @ 110 kg" },
  ],
};

export const recoveryData: RecoveryData = {
  readiness: 74,
  status: "Moderate — train, but cap intensity",
  recommendation:
    "Green-light for a moderate session. Keep top sets at RPE 7 and skip failure work. Prioritise a 40-minute zone 2 block instead of intervals.",
  sleep: {
    hours: 6.7,
    efficiencyPercent: 88,
    note: "Self-reported — 48 min below your 7h 30m floor",
  },
  restingHr: 48,
  hrvMs: null,
  soreness: [
    { area: "Quads", level: 3 },
    { area: "Glutes", level: 2 },
    { area: "Lower back", level: 2 },
    { area: "Shoulders", level: 1 },
    { area: "Hamstrings", level: 3 },
  ],
  fatigue: 3,
  stress: 2,
  trend: [
    { date: "Thu", readiness: 81 },
    { date: "Fri", readiness: 78 },
    { date: "Sat", readiness: 86 },
    { date: "Sun", readiness: 69 },
    { date: "Mon", readiness: 72 },
    { date: "Tue", readiness: 83 },
    { date: "Wed", readiness: 74 },
  ],
  placeholders: [
    "HRV is a placeholder — connect a wearable to populate overnight HRV.",
    "Sleep stages and respiratory rate require a connected device.",
    "Resting HR is derived from your logged morning readings, not continuous data.",
  ],
};

export const coachData: CoachData = {
  today: {
    headline: "Train as planned, then defend recovery",
    body: "Your acute:chronic load ratio sits at 1.16 — productive, not reckless. Today's prescription stands, but the marginal gain now comes from sleep and protein rather than extra volume.",
    bullets: [
      "Cap the evening session at 60 minutes of working time",
      "Top set RPE 8, no grinders past RPE 9",
      "25 g protein within 60 minutes of finishing",
    ],
  },
  tomorrow: {
    headline: "Aerobic maintenance + upper pull",
    body: "Lower body needs 48 hours after 150 kg triples. Keep tomorrow low-impact and pull-dominant to preserve the squat trend line.",
    blocks: [
      { name: "Zone 2 bike", detail: "40 min · HR 125-140 · nasal breathing only" },
      { name: "Weighted pull-up", detail: "4×5 @ +20 kg · RPE 7" },
      { name: "Chest-supported row", detail: "3×12 @ 60 kg" },
      { name: "Rear delt + rotator cuff", detail: "3×15 · light, controlled" },
    ],
  },
  observations: [
    {
      id: "o1",
      title: "Squat velocity is holding at higher load",
      detail:
        "Three consecutive weeks of load increases with RPE stable at 8 — you are not yet near your ceiling.",
      severity: "good",
    },
    {
      id: "o2",
      title: "Cardio work is drifting harder than prescribed",
      detail: "31% of aerobic minutes landed in vigorous/peak this week versus a 20% target.",
      severity: "warn",
    },
    {
      id: "o3",
      title: "Pull volume trails push volume by 18%",
      detail: "Horizontal pulling is the gap. Two extra row sets per week would rebalance it.",
      severity: "info",
    },
  ],
  riskNotes: [
    {
      id: "r1",
      title: "Acute load 18% above chronic",
      detail:
        "Still inside the sweet spot (0.8-1.3) but trending up for a third week. Plan a deload in 10-14 days.",
      severity: "warn",
    },
    {
      id: "r2",
      title: "Sleep debt accumulating",
      detail:
        "-2h 14m across the last four nights. This is the single strongest predictor of a missed session for you.",
      severity: "risk",
    },
    {
      id: "r3",
      title: "Hamstring soreness at 3/5 twice this week",
      detail: "Keep RDL load flat next session and add 5 minutes of posterior chain warm-up.",
      severity: "warn",
    },
  ],
  adjustments: [
    {
      id: "a1",
      title: "Hold squat load for one more week",
      detail: "Repeat 150 kg 5×3 before progressing. Consolidate rather than chase.",
      severity: "good",
    },
    {
      id: "a2",
      title: "Convert one interval session to zone 2",
      detail:
        "Swap Monday's rower intervals for 45 minutes steady to pull vigorous minutes back to target.",
      severity: "info",
    },
    {
      id: "a3",
      title: "Add 2 sets of horizontal pull weekly",
      detail:
        "Chest-supported row, 12-15 reps, RPE 8. Rebalances push:pull ratio inside three weeks.",
      severity: "info",
    },
  ],
  starterQuestions: [
    "Should I deload next week?",
    "Why did my readiness drop on Sunday?",
    "How do I add 10 kg to my squat by December?",
    "Am I eating enough protein for this volume?",
  ],
};
