/**
 * Legacy IronDesk workout program — authoritative source.
 *
 * Recovered verbatim from the original `IronDesk.jsx` (`PROGRAM_HOME` +
 * `PROGRAM_GYM`): 12 templates / 62 prescribed movements. This module is the
 * single source of truth for the demo-mode template browser and mirrors, row
 * for row, the system templates seeded into the database by migration
 * `..._legacy_workout_templates.sql` (matched on `sourceKey`).
 *
 * Legacy numeric load guidance ("315–345") is POUNDS — `sourceLoadUnit: "lb"`.
 * Never treat those numbers as kilograms.
 */
import type { WorkoutTemplate } from "./types";

export const LEGACY_SOURCE_NAME = "IronDesk.jsx";

/** Demo-mode templates. Ids are the stable source keys, not database uuids. */
export const LEGACY_TEMPLATES: WorkoutTemplate[] = [
  {
    id: "legacy-home-chest",
    isSystem: true,
    sourceKey: "legacy-home-chest",
    sourceName: "IronDesk.jsx",
    sourceVersion: 1,
    name: "Chest · Home",
    focus: "HEAVY DAY · bench-led, long rest, no pump chase",
    notes: null,
    kind: "strength",
    environment: "home",
    workoutType: "heavy",
    category: "strength",
    level: null,
    estimatedMinutes: 60,
    tags: ["home", "heavy", "chest"],
    sortOrder: 100,
    legacyDayId: "Chest",
    exercises: [
      {
        id: "legacy-home-chest-0",
        position: 0,
        name: "Bench Press",
        exerciseId: null,
        canonicalName: "Barbell Bench Press",
        targetSets: 4,
        targetReps: "4",
        targetRpe: 8,
        restSeconds: 180,
        loadGuidance: "315–345",
        sourceLoadUnit: "lb",
        isDropSet: false,
        isHeavy: true,
        notes: "Top strength lift — rest 3 min",
      },
      {
        id: "legacy-home-chest-1",
        position: 1,
        name: "Incline Barbell / DB Press",
        exerciseId: null,
        canonicalName: "Incline Bench Press",
        targetSets: 3,
        targetReps: "5",
        targetRpe: 8,
        restSeconds: 180,
        loadGuidance: "heavy",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: true,
        notes: "Upper chest",
      },
      {
        id: "legacy-home-chest-2",
        position: 2,
        name: "Flat DB Press",
        exerciseId: null,
        canonicalName: "Dumbbell Bench Press",
        targetSets: 3,
        targetReps: "6",
        targetRpe: 8,
        restSeconds: 90,
        loadGuidance: "heavy",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Stretch at bottom",
      },
      {
        id: "legacy-home-chest-3",
        position: 3,
        name: "Weighted Dip",
        exerciseId: null,
        canonicalName: "Dip",
        targetSets: 2,
        targetReps: "6",
        targetRpe: 8,
        restSeconds: 90,
        loadGuidance: "add load",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Optional finisher",
      },
    ],
  },
  {
    id: "legacy-home-arms",
    isSystem: true,
    sourceKey: "legacy-home-arms",
    sourceName: "IronDesk.jsx",
    sourceVersion: 1,
    name: "Arms · Home",
    focus: "PUMP DAY · supersets, short rest, chase the burn",
    notes: null,
    kind: "strength",
    environment: "home",
    workoutType: "pump",
    category: "strength",
    level: null,
    estimatedMinutes: 50,
    tags: ["home", "pump", "arms"],
    sortOrder: 101,
    legacyDayId: "Arms",
    exercises: [
      {
        id: "legacy-home-arms-0",
        position: 0,
        name: "EZ Bar Curl",
        exerciseId: null,
        canonicalName: "Barbell Curl",
        targetSets: 3,
        targetReps: "10",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "moderate",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Strict",
      },
      {
        id: "legacy-home-arms-1",
        position: 1,
        name: "Tricep Pushdown",
        exerciseId: null,
        canonicalName: "Triceps Pushdown",
        targetSets: 3,
        targetReps: "12",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "moderate",
        sourceLoadUnit: null,
        isDropSet: true,
        isHeavy: false,
        notes: "Superset w/ curls · drop last set",
      },
      {
        id: "legacy-home-arms-2",
        position: 2,
        name: "Hammer Curl",
        exerciseId: null,
        canonicalName: "Incline Dumbbell Curl",
        targetSets: 3,
        targetReps: "12",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "moderate",
        sourceLoadUnit: null,
        isDropSet: true,
        isHeavy: false,
        notes: "Drop last set",
      },
      {
        id: "legacy-home-arms-3",
        position: 3,
        name: "Overhead Tricep Ext",
        exerciseId: null,
        canonicalName: "Skullcrusher",
        targetSets: 3,
        targetReps: "12",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "moderate",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Full stretch",
      },
      {
        id: "legacy-home-arms-4",
        position: 4,
        name: "Wide-Grip Curl",
        exerciseId: null,
        canonicalName: "Barbell Curl",
        targetSets: 2,
        targetReps: "15",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "light",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Burnout",
      },
      {
        id: "legacy-home-arms-5",
        position: 5,
        name: "Cable Kickback",
        exerciseId: null,
        canonicalName: "Triceps Pushdown",
        targetSets: 2,
        targetReps: "15",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "light",
        sourceLoadUnit: null,
        isDropSet: true,
        isHeavy: false,
        notes: "Squeeze · drop last set",
      },
    ],
  },
  {
    id: "legacy-home-back",
    isSystem: true,
    sourceKey: "legacy-home-back",
    sourceName: "IronDesk.jsx",
    sourceVersion: 1,
    name: "Back · Home",
    focus: "HEAVY DAY · deadlift + rows, long rest",
    notes: null,
    kind: "strength",
    environment: "home",
    workoutType: "heavy",
    category: "strength",
    level: null,
    estimatedMinutes: 60,
    tags: ["home", "heavy", "back"],
    sortOrder: 102,
    legacyDayId: "Back",
    exercises: [
      {
        id: "legacy-home-back-0",
        position: 0,
        name: "Deadlift",
        exerciseId: null,
        canonicalName: "Conventional Deadlift",
        targetSets: 4,
        targetReps: "3",
        targetRpe: 8,
        restSeconds: 180,
        loadGuidance: "405–455",
        sourceLoadUnit: "lb",
        isDropSet: false,
        isHeavy: true,
        notes: "Bar speed fast or stop",
      },
      {
        id: "legacy-home-back-1",
        position: 1,
        name: "Barbell Bent-Over Row",
        exerciseId: null,
        canonicalName: "Barbell Row",
        targetSets: 4,
        targetReps: "5",
        targetRpe: 8,
        restSeconds: 180,
        loadGuidance: "heavy",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: true,
        notes: "Controlled, no jerk",
      },
      {
        id: "legacy-home-back-2",
        position: 2,
        name: "Weighted Pull-up",
        exerciseId: null,
        canonicalName: "Pull-Up",
        targetSets: 3,
        targetReps: "5",
        targetRpe: 8,
        restSeconds: 90,
        loadGuidance: "add load",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Full hang",
      },
      {
        id: "legacy-home-back-3",
        position: 3,
        name: "One-Arm DB Row",
        exerciseId: null,
        canonicalName: "Dumbbell Row",
        targetSets: 3,
        targetReps: "6",
        targetRpe: 8,
        restSeconds: 90,
        loadGuidance: "heavy",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Stretch each rep",
      },
    ],
  },
  {
    id: "legacy-home-shoulders",
    isSystem: true,
    sourceKey: "legacy-home-shoulders",
    sourceName: "IronDesk.jsx",
    sourceVersion: 1,
    name: "Shoulders · Home",
    focus: "PUMP DAY · laterals & rear delts, chase the burn",
    notes: null,
    kind: "strength",
    environment: "home",
    workoutType: "pump",
    category: "strength",
    level: null,
    estimatedMinutes: 50,
    tags: ["home", "pump", "shoulders"],
    sortOrder: 103,
    legacyDayId: "Shoulders",
    exercises: [
      {
        id: "legacy-home-shoulders-0",
        position: 0,
        name: "Lateral Raises",
        exerciseId: null,
        canonicalName: "Lateral Raise",
        targetSets: 4,
        targetReps: "15",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "light, strict",
        sourceLoadUnit: null,
        isDropSet: true,
        isHeavy: false,
        notes: "Drop last set — no swing",
      },
      {
        id: "legacy-home-shoulders-1",
        position: 1,
        name: "DB Arnold Press",
        exerciseId: null,
        canonicalName: "Seated Dumbbell Press",
        targetSets: 3,
        targetReps: "12",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "moderate",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Full ROM",
      },
      {
        id: "legacy-home-shoulders-2",
        position: 2,
        name: "Cable Rear Delt Fly",
        exerciseId: null,
        canonicalName: "Rear Delt Fly",
        targetSets: 3,
        targetReps: "15",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "light",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Squeeze back",
      },
      {
        id: "legacy-home-shoulders-3",
        position: 3,
        name: "Reverse Pec Deck",
        exerciseId: null,
        canonicalName: "Rear Delt Fly",
        targetSets: 3,
        targetReps: "15",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "light",
        sourceLoadUnit: null,
        isDropSet: true,
        isHeavy: false,
        notes: "Drop last set",
      },
      {
        id: "legacy-home-shoulders-4",
        position: 4,
        name: "Shoulder Shrugs",
        exerciseId: null,
        canonicalName: "Farmer Carry",
        targetSets: 3,
        targetReps: "15",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "moderate",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Traps",
      },
      {
        id: "legacy-home-shoulders-5",
        position: 5,
        name: "Upright Row / Front Raise",
        exerciseId: null,
        canonicalName: "Lateral Raise",
        targetSets: 2,
        targetReps: "15",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "light",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Burnout",
      },
    ],
  },
  {
    id: "legacy-home-legs",
    isSystem: true,
    sourceKey: "legacy-home-legs",
    sourceName: "IronDesk.jsx",
    sourceVersion: 1,
    name: "Legs · Home",
    focus: "HEAVY DAY · squat-led, long rest",
    notes: null,
    kind: "strength",
    environment: "home",
    workoutType: "heavy",
    category: "strength",
    level: null,
    estimatedMinutes: 60,
    tags: ["home", "heavy", "legs"],
    sortOrder: 104,
    legacyDayId: "Legs",
    exercises: [
      {
        id: "legacy-home-legs-0",
        position: 0,
        name: "Back Squat",
        exerciseId: null,
        canonicalName: "Back Squat",
        targetSets: 4,
        targetReps: "4",
        targetRpe: 8,
        restSeconds: 180,
        loadGuidance: "385–425",
        sourceLoadUnit: "lb",
        isDropSet: false,
        isHeavy: true,
        notes: "Pins set — rest 3 min",
      },
      {
        id: "legacy-home-legs-1",
        position: 1,
        name: "Romanian Deadlift",
        exerciseId: null,
        canonicalName: "Romanian Deadlift",
        targetSets: 3,
        targetReps: "6",
        targetRpe: 8,
        restSeconds: 180,
        loadGuidance: "heavy",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: true,
        notes: "Hamstrings loaded",
      },
      {
        id: "legacy-home-legs-2",
        position: 2,
        name: "Front Squat / Hack Squat",
        exerciseId: null,
        canonicalName: "Front Squat",
        targetSets: 3,
        targetReps: "6",
        targetRpe: 8,
        restSeconds: 90,
        loadGuidance: "moderate-heavy",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Quad focus",
      },
      {
        id: "legacy-home-legs-3",
        position: 3,
        name: "Leg Curl",
        exerciseId: null,
        canonicalName: "Leg Curl",
        targetSets: 3,
        targetReps: "8",
        targetRpe: 8,
        restSeconds: 90,
        loadGuidance: "moderate",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Hamstring isolation",
      },
    ],
  },
  {
    id: "legacy-home-calves-plus-abs",
    isSystem: true,
    sourceKey: "legacy-home-calves-plus-abs",
    sourceName: "IronDesk.jsx",
    sourceVersion: 1,
    name: "Calves+Abs · Home",
    focus: "PUMP DAY · high rep, drop sets",
    notes: null,
    kind: "strength",
    environment: "home",
    workoutType: "pump",
    category: "strength",
    level: null,
    estimatedMinutes: 50,
    tags: ["home", "pump", "calves-plus-abs"],
    sortOrder: 105,
    legacyDayId: "Calves+Abs",
    exercises: [
      {
        id: "legacy-home-calves-plus-abs-0",
        position: 0,
        name: "Standing Calf Raise",
        exerciseId: null,
        canonicalName: "Standing Calf Raise",
        targetSets: 4,
        targetReps: "15",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "loaded",
        sourceLoadUnit: null,
        isDropSet: true,
        isHeavy: false,
        notes: "Pause at top · drop last set",
      },
      {
        id: "legacy-home-calves-plus-abs-1",
        position: 1,
        name: "Seated Calf Raise",
        exerciseId: null,
        canonicalName: "Standing Calf Raise",
        targetSets: 3,
        targetReps: "20",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "moderate",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Soleus",
      },
      {
        id: "legacy-home-calves-plus-abs-2",
        position: 2,
        name: "Hanging Leg Raise",
        exerciseId: null,
        canonicalName: "Hanging Leg Raise",
        targetSets: 3,
        targetReps: "15",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "bodyweight",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Slow negative",
      },
      {
        id: "legacy-home-calves-plus-abs-3",
        position: 3,
        name: "Cable Crunch",
        exerciseId: null,
        canonicalName: "Cable Crunch",
        targetSets: 3,
        targetReps: "15",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "loaded",
        sourceLoadUnit: null,
        isDropSet: true,
        isHeavy: false,
        notes: "Drop last set",
      },
      {
        id: "legacy-home-calves-plus-abs-4",
        position: 4,
        name: "Weighted Sit-Ups",
        exerciseId: null,
        canonicalName: "Cable Crunch",
        targetSets: 3,
        targetReps: "20",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "light plate",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Full range",
      },
      {
        id: "legacy-home-calves-plus-abs-5",
        position: 5,
        name: "Air Bike",
        exerciseId: null,
        canonicalName: "Air Bike Intervals",
        targetSets: 2,
        targetReps: "30",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "bodyweight",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Burnout",
      },
    ],
  },
  {
    id: "legacy-gym-chest",
    isSystem: true,
    sourceKey: "legacy-gym-chest",
    sourceName: "IronDesk.jsx",
    sourceVersion: 1,
    name: "Chest · Gym",
    focus: "HEAVY DAY · bench-led + machine volume",
    notes: null,
    kind: "strength",
    environment: "gym",
    workoutType: "heavy",
    category: "strength",
    level: null,
    estimatedMinutes: 60,
    tags: ["gym", "heavy", "chest"],
    sortOrder: 200,
    legacyDayId: "Chest",
    exercises: [
      {
        id: "legacy-gym-chest-0",
        position: 0,
        name: "Barbell Bench Press",
        exerciseId: null,
        canonicalName: "Barbell Bench Press",
        targetSets: 4,
        targetReps: "4",
        targetRpe: 8,
        restSeconds: 180,
        loadGuidance: "315–345",
        sourceLoadUnit: "lb",
        isDropSet: false,
        isHeavy: true,
        notes: "Top strength lift — rest 3 min",
      },
      {
        id: "legacy-gym-chest-1",
        position: 1,
        name: "Incline Smith / Leverage Press",
        exerciseId: null,
        canonicalName: "Machine Chest Press",
        targetSets: 3,
        targetReps: "6",
        targetRpe: 8,
        restSeconds: 180,
        loadGuidance: "heavy",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: true,
        notes: "Machine — upper chest",
      },
      {
        id: "legacy-gym-chest-2",
        position: 2,
        name: "Pec Deck / Cable Fly",
        exerciseId: null,
        canonicalName: "Cable Fly",
        targetSets: 3,
        targetReps: "10",
        targetRpe: 8,
        restSeconds: 90,
        loadGuidance: "moderate",
        sourceLoadUnit: null,
        isDropSet: true,
        isHeavy: false,
        notes: "Squeeze · drop last set",
      },
      {
        id: "legacy-gym-chest-3",
        position: 3,
        name: "Weighted Dip",
        exerciseId: null,
        canonicalName: "Dip",
        targetSets: 2,
        targetReps: "8",
        targetRpe: 8,
        restSeconds: 90,
        loadGuidance: "add load",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Finisher",
      },
    ],
  },
  {
    id: "legacy-gym-arms",
    isSystem: true,
    sourceKey: "legacy-gym-arms",
    sourceName: "IronDesk.jsx",
    sourceVersion: 1,
    name: "Arms · Gym",
    focus: "PUMP DAY · cables & machines, chase the burn",
    notes: null,
    kind: "strength",
    environment: "gym",
    workoutType: "pump",
    category: "strength",
    level: null,
    estimatedMinutes: 50,
    tags: ["gym", "pump", "arms"],
    sortOrder: 201,
    legacyDayId: "Arms",
    exercises: [
      {
        id: "legacy-gym-arms-0",
        position: 0,
        name: "Cable Tricep Pushdown",
        exerciseId: null,
        canonicalName: "Triceps Pushdown",
        targetSets: 3,
        targetReps: "12",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "moderate",
        sourceLoadUnit: null,
        isDropSet: true,
        isHeavy: false,
        notes: "Superset · drop last set",
      },
      {
        id: "legacy-gym-arms-1",
        position: 1,
        name: "EZ Bar Curl",
        exerciseId: null,
        canonicalName: "Barbell Curl",
        targetSets: 3,
        targetReps: "10",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "moderate",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Strict",
      },
      {
        id: "legacy-gym-arms-2",
        position: 2,
        name: "Cable Curl",
        exerciseId: null,
        canonicalName: "Barbell Curl",
        targetSets: 3,
        targetReps: "12",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "moderate",
        sourceLoadUnit: null,
        isDropSet: true,
        isHeavy: false,
        notes: "Constant tension · drop last",
      },
      {
        id: "legacy-gym-arms-3",
        position: 3,
        name: "Overhead Cable Ext",
        exerciseId: null,
        canonicalName: "Skullcrusher",
        targetSets: 3,
        targetReps: "12",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "moderate",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Full stretch",
      },
      {
        id: "legacy-gym-arms-4",
        position: 4,
        name: "Machine Preacher Curl",
        exerciseId: null,
        canonicalName: "Barbell Curl",
        targetSets: 2,
        targetReps: "15",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "light",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Burnout",
      },
      {
        id: "legacy-gym-arms-5",
        position: 5,
        name: "Rope Hammer Curl",
        exerciseId: null,
        canonicalName: "Incline Dumbbell Curl",
        targetSets: 2,
        targetReps: "15",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "light",
        sourceLoadUnit: null,
        isDropSet: true,
        isHeavy: false,
        notes: "Drop last set",
      },
    ],
  },
  {
    id: "legacy-gym-back",
    isSystem: true,
    sourceKey: "legacy-gym-back",
    sourceName: "IronDesk.jsx",
    sourceVersion: 1,
    name: "Back · Gym",
    focus: "HEAVY DAY · deadlift + cable/machine rows",
    notes: null,
    kind: "strength",
    environment: "gym",
    workoutType: "heavy",
    category: "strength",
    level: null,
    estimatedMinutes: 60,
    tags: ["gym", "heavy", "back"],
    sortOrder: 202,
    legacyDayId: "Back",
    exercises: [
      {
        id: "legacy-gym-back-0",
        position: 0,
        name: "Deadlift",
        exerciseId: null,
        canonicalName: "Conventional Deadlift",
        targetSets: 4,
        targetReps: "3",
        targetRpe: 8,
        restSeconds: 180,
        loadGuidance: "405–455",
        sourceLoadUnit: "lb",
        isDropSet: false,
        isHeavy: true,
        notes: "Bar speed fast or stop",
      },
      {
        id: "legacy-gym-back-1",
        position: 1,
        name: "Lat Pulldown / Weighted Pull-up",
        exerciseId: null,
        canonicalName: "Lat Pulldown",
        targetSets: 4,
        targetReps: "8",
        targetRpe: 8,
        restSeconds: 180,
        loadGuidance: "heavy",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: true,
        notes: "Full stretch",
      },
      {
        id: "legacy-gym-back-2",
        position: 2,
        name: "Seated Cable Row",
        exerciseId: null,
        canonicalName: "Seated Cable Row",
        targetSets: 3,
        targetReps: "8",
        targetRpe: 8,
        restSeconds: 90,
        loadGuidance: "heavy",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Squeeze shoulder blades",
      },
      {
        id: "legacy-gym-back-3",
        position: 3,
        name: "Hammer / Machine Row",
        exerciseId: null,
        canonicalName: "Seated Cable Row",
        targetSets: 3,
        targetReps: "10",
        targetRpe: 8,
        restSeconds: 90,
        loadGuidance: "moderate",
        sourceLoadUnit: null,
        isDropSet: true,
        isHeavy: false,
        notes: "Drop last set",
      },
      {
        id: "legacy-gym-back-4",
        position: 4,
        name: "Straight-Arm Pulldown",
        exerciseId: null,
        canonicalName: "Lat Pulldown",
        targetSets: 2,
        targetReps: "15",
        targetRpe: 8,
        restSeconds: 90,
        loadGuidance: "light",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Lat isolation",
      },
    ],
  },
  {
    id: "legacy-gym-shoulders",
    isSystem: true,
    sourceKey: "legacy-gym-shoulders",
    sourceName: "IronDesk.jsx",
    sourceVersion: 1,
    name: "Shoulders · Gym",
    focus: "PUMP DAY · cable laterals & machine presses",
    notes: null,
    kind: "strength",
    environment: "gym",
    workoutType: "pump",
    category: "strength",
    level: null,
    estimatedMinutes: 50,
    tags: ["gym", "pump", "shoulders"],
    sortOrder: 203,
    legacyDayId: "Shoulders",
    exercises: [
      {
        id: "legacy-gym-shoulders-0",
        position: 0,
        name: "Cable Lateral Raise",
        exerciseId: null,
        canonicalName: "Lateral Raise",
        targetSets: 4,
        targetReps: "15",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "light",
        sourceLoadUnit: null,
        isDropSet: true,
        isHeavy: false,
        notes: "Constant tension · drop last set",
      },
      {
        id: "legacy-gym-shoulders-1",
        position: 1,
        name: "Machine Shoulder Press",
        exerciseId: null,
        canonicalName: "Seated Dumbbell Press",
        targetSets: 3,
        targetReps: "12",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "moderate",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Full ROM",
      },
      {
        id: "legacy-gym-shoulders-2",
        position: 2,
        name: "Reverse Pec Deck",
        exerciseId: null,
        canonicalName: "Rear Delt Fly",
        targetSets: 3,
        targetReps: "15",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "light",
        sourceLoadUnit: null,
        isDropSet: true,
        isHeavy: false,
        notes: "Rear delts · drop last set",
      },
      {
        id: "legacy-gym-shoulders-3",
        position: 3,
        name: "Cable Rear Delt Fly",
        exerciseId: null,
        canonicalName: "Rear Delt Fly",
        targetSets: 3,
        targetReps: "15",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "light",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Squeeze back",
      },
      {
        id: "legacy-gym-shoulders-4",
        position: 4,
        name: "Machine / DB Shrugs",
        exerciseId: null,
        canonicalName: "Farmer Carry",
        targetSets: 3,
        targetReps: "15",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "heavy",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Traps",
      },
      {
        id: "legacy-gym-shoulders-5",
        position: 5,
        name: "Cable Upright Row",
        exerciseId: null,
        canonicalName: "Lateral Raise",
        targetSets: 2,
        targetReps: "15",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "light",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Burnout",
      },
    ],
  },
  {
    id: "legacy-gym-legs",
    isSystem: true,
    sourceKey: "legacy-gym-legs",
    sourceName: "IronDesk.jsx",
    sourceVersion: 1,
    name: "Legs · Gym",
    focus: "HEAVY DAY · squat + leg press & machines",
    notes: null,
    kind: "strength",
    environment: "gym",
    workoutType: "heavy",
    category: "strength",
    level: null,
    estimatedMinutes: 60,
    tags: ["gym", "heavy", "legs"],
    sortOrder: 204,
    legacyDayId: "Legs",
    exercises: [
      {
        id: "legacy-gym-legs-0",
        position: 0,
        name: "Back Squat",
        exerciseId: null,
        canonicalName: "Back Squat",
        targetSets: 4,
        targetReps: "4",
        targetRpe: 8,
        restSeconds: 180,
        loadGuidance: "385–425",
        sourceLoadUnit: "lb",
        isDropSet: false,
        isHeavy: true,
        notes: "Rest 3 min",
      },
      {
        id: "legacy-gym-legs-1",
        position: 1,
        name: "Leg Press",
        exerciseId: null,
        canonicalName: "Leg Press",
        targetSets: 3,
        targetReps: "8",
        targetRpe: 8,
        restSeconds: 180,
        loadGuidance: "heavy",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: true,
        notes: "Full depth",
      },
      {
        id: "legacy-gym-legs-2",
        position: 2,
        name: "Hack Squat",
        exerciseId: null,
        canonicalName: "Front Squat",
        targetSets: 3,
        targetReps: "8",
        targetRpe: 8,
        restSeconds: 90,
        loadGuidance: "moderate-heavy",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Quad focus",
      },
      {
        id: "legacy-gym-legs-3",
        position: 3,
        name: "Lying Leg Curl",
        exerciseId: null,
        canonicalName: "Leg Curl",
        targetSets: 3,
        targetReps: "10",
        targetRpe: 8,
        restSeconds: 90,
        loadGuidance: "moderate",
        sourceLoadUnit: null,
        isDropSet: true,
        isHeavy: false,
        notes: "Hamstrings · drop last set",
      },
      {
        id: "legacy-gym-legs-4",
        position: 4,
        name: "Leg Extension",
        exerciseId: null,
        canonicalName: "Leg Extension",
        targetSets: 3,
        targetReps: "12",
        targetRpe: 8,
        restSeconds: 90,
        loadGuidance: "moderate",
        sourceLoadUnit: null,
        isDropSet: true,
        isHeavy: false,
        notes: "Quads · drop last set",
      },
    ],
  },
  {
    id: "legacy-gym-calves-plus-abs",
    isSystem: true,
    sourceKey: "legacy-gym-calves-plus-abs",
    sourceName: "IronDesk.jsx",
    sourceVersion: 1,
    name: "Calves+Abs · Gym",
    focus: "PUMP DAY · machines, high rep, drop sets",
    notes: null,
    kind: "strength",
    environment: "gym",
    workoutType: "pump",
    category: "strength",
    level: null,
    estimatedMinutes: 50,
    tags: ["gym", "pump", "calves-plus-abs"],
    sortOrder: 205,
    legacyDayId: "Calves+Abs",
    exercises: [
      {
        id: "legacy-gym-calves-plus-abs-0",
        position: 0,
        name: "Standing Calf Machine",
        exerciseId: null,
        canonicalName: "Standing Calf Raise",
        targetSets: 4,
        targetReps: "15",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "heavy",
        sourceLoadUnit: null,
        isDropSet: true,
        isHeavy: false,
        notes: "Pause at top · drop last set",
      },
      {
        id: "legacy-gym-calves-plus-abs-1",
        position: 1,
        name: "Seated Calf Machine",
        exerciseId: null,
        canonicalName: "Standing Calf Raise",
        targetSets: 3,
        targetReps: "20",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "moderate",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Soleus",
      },
      {
        id: "legacy-gym-calves-plus-abs-2",
        position: 2,
        name: "Cable Crunch",
        exerciseId: null,
        canonicalName: "Cable Crunch",
        targetSets: 3,
        targetReps: "15",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "loaded",
        sourceLoadUnit: null,
        isDropSet: true,
        isHeavy: false,
        notes: "Drop last set",
      },
      {
        id: "legacy-gym-calves-plus-abs-3",
        position: 3,
        name: "Captain's Chair Leg Raise",
        exerciseId: null,
        canonicalName: "Hanging Leg Raise",
        targetSets: 3,
        targetReps: "15",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "bodyweight",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Slow negative",
      },
      {
        id: "legacy-gym-calves-plus-abs-4",
        position: 4,
        name: "Weighted Sit-Ups",
        exerciseId: null,
        canonicalName: "Cable Crunch",
        targetSets: 3,
        targetReps: "20",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "light plate",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Full range",
      },
      {
        id: "legacy-gym-calves-plus-abs-5",
        position: 5,
        name: "Air Bike",
        exerciseId: null,
        canonicalName: "Air Bike Intervals",
        targetSets: 2,
        targetReps: "30",
        targetRpe: 8,
        restSeconds: 60,
        loadGuidance: "bodyweight",
        sourceLoadUnit: null,
        isDropSet: false,
        isHeavy: false,
        notes: "Burnout",
      },
    ],
  },
];
