/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ExercisesIndexRouteImport } from './routes/exercises/index'
import { Route as ExercisesExerciseIdRouteImport } from './routes/exercises/$exerciseId'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicHealthConnectIngestRouteImport } from './routes/api/public/health-connect/ingest'
import { Route as ApiPublicHealthConnectPairRouteImport } from './routes/api/public/health-connect/pair'
import { Route as ApiPublicHealthConnectUnpairRouteImport } from './routes/api/public/health-connect/unpair'
import { Route as ApiPublicConnectIqV1PairRouteImport } from './routes/api/public/connect-iq/v1/pair'
import { Route as ApiPublicConnectIqV1UnpairRouteImport } from './routes/api/public/connect-iq/v1/unpair'
import { Route as ApiPublicConnectIqV1WorkoutEventsRouteImport } from './routes/api/public/connect-iq/v1/workout-events'
import { Route as ApiPublicConnectIqV1WorkoutsActiveRouteImport } from './routes/api/public/connect-iq/v1/workouts/active'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesExerciseIdRoute = ExercisesExerciseIdRouteImport.update({
  id: '/exercises/$exerciseId',
  path: '/exercises/$exerciseId',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHealthConnectIngestRoute =
  ApiPublicHealthConnectIngestRouteImport.update({
    id: '/api/public/health-connect/ingest',
    path: '/api/public/health-connect/ingest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHealthConnectPairRoute =
  ApiPublicHealthConnectPairRouteImport.update({
    id: '/api/public/health-connect/pair',
    path: '/api/public/health-connect/pair',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHealthConnectUnpairRoute =
  ApiPublicHealthConnectUnpairRouteImport.update({
    id: '/api/public/health-connect/unpair',
    path: '/api/public/health-connect/unpair',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicConnectIqV1PairRoute =
  ApiPublicConnectIqV1PairRouteImport.update({
    id: '/api/public/connect-iq/v1/pair',
    path: '/api/public/connect-iq/v1/pair',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicConnectIqV1UnpairRoute =
  ApiPublicConnectIqV1UnpairRouteImport.update({
    id: '/api/public/connect-iq/v1/unpair',
    path: '/api/public/connect-iq/v1/unpair',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicConnectIqV1WorkoutEventsRoute =
  ApiPublicConnectIqV1WorkoutEventsRouteImport.update({
    id: '/api/public/connect-iq/v1/workout-events',
    path: '/api/public/connect-iq/v1/workout-events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicConnectIqV1WorkoutsActiveRoute =
  ApiPublicConnectIqV1WorkoutsActiveRouteImport.update({
    id: '/api/public/connect-iq/v1/workouts/active',
    path: '/api/public/connect-iq/v1/workouts/active',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/connections': typeof ConnectionsRoute
  '/history': typeof HistoryRoute
  '/mcp': typeof McpRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/program': typeof ProgramRoute
  '/progress': typeof ProgressRoute
  '/recovery': typeof RecoveryRoute
  '/settings': typeof SettingsRoute
  '/workout': typeof WorkoutRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/health-connect/ingest': typeof ApiPublicHealthConnectIngestRoute
  '/api/public/health-connect/pair': typeof ApiPublicHealthConnectPairRoute
  '/api/public/health-connect/unpair': typeof ApiPublicHealthConnectUnpairRoute
  '/api/public/connect-iq/v1/pair': typeof ApiPublicConnectIqV1PairRoute
  '/api/public/connect-iq/v1/unpair': typeof ApiPublicConnectIqV1UnpairRoute
  '/api/public/connect-iq/v1/workout-events': typeof ApiPublicConnectIqV1WorkoutEventsRoute
  '/api/public/connect-iq/v1/workouts/active': typeof ApiPublicConnectIqV1WorkoutsActiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/connections': typeof ConnectionsRoute
  '/history': typeof HistoryRoute
  '/mcp': typeof McpRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/program': typeof ProgramRoute
  '/progress': typeof ProgressRoute
  '/recovery': typeof RecoveryRoute
  '/settings': typeof SettingsRoute
  '/workout': typeof WorkoutRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/exercises': typeof ExercisesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/health-connect/ingest': typeof ApiPublicHealthConnectIngestRoute
  '/api/public/health-connect/pair': typeof ApiPublicHealthConnectPairRoute
  '/api/public/health-connect/unpair': typeof ApiPublicHealthConnectUnpairRoute
  '/api/public/connect-iq/v1/pair': typeof ApiPublicConnectIqV1PairRoute
  '/api/public/connect-iq/v1/unpair': typeof ApiPublicConnectIqV1UnpairRoute
  '/api/public/connect-iq/v1/workout-events': typeof ApiPublicConnectIqV1WorkoutEventsRoute
  '/api/public/connect-iq/v1/workouts/active': typeof ApiPublicConnectIqV1WorkoutsActiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/connections': typeof ConnectionsRoute
  '/history': typeof HistoryRoute
  '/mcp': typeof McpRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/program': typeof ProgramRoute
  '/progress': typeof ProgressRoute
  '/recovery': typeof RecoveryRoute
  '/settings': typeof SettingsRoute
  '/workout': typeof WorkoutRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/health-connect/ingest': typeof ApiPublicHealthConnectIngestRoute
  '/api/public/health-connect/pair': typeof ApiPublicHealthConnectPairRoute
  '/api/public/health-connect/unpair': typeof ApiPublicHealthConnectUnpairRoute
  '/api/public/connect-iq/v1/pair': typeof ApiPublicConnectIqV1PairRoute
  '/api/public/connect-iq/v1/unpair': typeof ApiPublicConnectIqV1UnpairRoute
  '/api/public/connect-iq/v1/workout-events': typeof ApiPublicConnectIqV1WorkoutEventsRoute
  '/api/public/connect-iq/v1/workouts/active': typeof ApiPublicConnectIqV1WorkoutsActiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/coach'
    | '/connections'
    | '/history'
    | '/mcp'
    | '/nutrition'
    | '/onboarding'
    | '/program'
    | '/progress'
    | '/recovery'
    | '/settings'
    | '/workout'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/exercises/$exerciseId'
    | '/exercises/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/health-connect/ingest'
    | '/api/public/health-connect/pair'
    | '/api/public/health-connect/unpair'
    | '/api/public/connect-iq/v1/pair'
    | '/api/public/connect-iq/v1/unpair'
    | '/api/public/connect-iq/v1/workout-events'
    | '/api/public/connect-iq/v1/workouts/active'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/coach'
    | '/connections'
    | '/history'
    | '/mcp'
    | '/nutrition'
    | '/onboarding'
    | '/program'
    | '/progress'
    | '/recovery'
    | '/settings'
    | '/workout'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/exercises/$exerciseId'
    | '/exercises'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/health-connect/ingest'
    | '/api/public/health-connect/pair'
    | '/api/public/health-connect/unpair'
    | '/api/public/connect-iq/v1/pair'
    | '/api/public/connect-iq/v1/unpair'
    | '/api/public/connect-iq/v1/workout-events'
    | '/api/public/connect-iq/v1/workouts/active'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/coach'
    | '/connections'
    | '/history'
    | '/mcp'
    | '/nutrition'
    | '/onboarding'
    | '/program'
    | '/progress'
    | '/recovery'
    | '/settings'
    | '/workout'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/exercises/$exerciseId'
    | '/exercises/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/health-connect/ingest'
    | '/api/public/health-connect/pair'
    | '/api/public/health-connect/unpair'
    | '/api/public/connect-iq/v1/pair'
    | '/api/public/connect-iq/v1/unpair'
    | '/api/public/connect-iq/v1/workout-events'
    | '/api/public/connect-iq/v1/workouts/active'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CoachRoute: typeof CoachRoute
  ConnectionsRoute: typeof ConnectionsRoute
  HistoryRoute: typeof HistoryRoute
  McpRoute: typeof McpRoute
  NutritionRoute: typeof NutritionRoute
  OnboardingRoute: typeof OnboardingRoute
  ProgramRoute: typeof ProgramRoute
  ProgressRoute: typeof ProgressRoute
  RecoveryRoute: typeof RecoveryRoute
  SettingsRoute: typeof SettingsRoute
  WorkoutRoute: typeof WorkoutRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ExercisesExerciseIdRoute: typeof ExercisesExerciseIdRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHealthConnectIngestRoute: typeof ApiPublicHealthConnectIngestRoute
  ApiPublicHealthConnectPairRoute: typeof ApiPublicHealthConnectPairRoute
  ApiPublicHealthConnectUnpairRoute: typeof ApiPublicHealthConnectUnpairRoute
  ApiPublicConnectIqV1PairRoute: typeof ApiPublicConnectIqV1PairRoute
  ApiPublicConnectIqV1UnpairRoute: typeof ApiPublicConnectIqV1UnpairRoute
  ApiPublicConnectIqV1WorkoutEventsRoute: typeof ApiPublicConnectIqV1WorkoutEventsRoute
  ApiPublicConnectIqV1WorkoutsActiveRoute: typeof ApiPublicConnectIqV1WorkoutsActiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises/'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$exerciseId': {
      id: '/exercises/$exerciseId'
      path: '/exercises/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof ExercisesExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health-connect/ingest': {
      id: '/api/public/health-connect/ingest'
      path: '/api/public/health-connect/ingest'
      fullPath: '/api/public/health-connect/ingest'
      preLoaderRoute: typeof ApiPublicHealthConnectIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health-connect/pair': {
      id: '/api/public/health-connect/pair'
      path: '/api/public/health-connect/pair'
      fullPath: '/api/public/health-connect/pair'
      preLoaderRoute: typeof ApiPublicHealthConnectPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health-connect/unpair': {
      id: '/api/public/health-connect/unpair'
      path: '/api/public/health-connect/unpair'
      fullPath: '/api/public/health-connect/unpair'
      preLoaderRoute: typeof ApiPublicHealthConnectUnpairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/connect-iq/v1/pair': {
      id: '/api/public/connect-iq/v1/pair'
      path: '/api/public/connect-iq/v1/pair'
      fullPath: '/api/public/connect-iq/v1/pair'
      preLoaderRoute: typeof ApiPublicConnectIqV1PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/connect-iq/v1/unpair': {
      id: '/api/public/connect-iq/v1/unpair'
      path: '/api/public/connect-iq/v1/unpair'
      fullPath: '/api/public/connect-iq/v1/unpair'
      preLoaderRoute: typeof ApiPublicConnectIqV1UnpairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/connect-iq/v1/workout-events': {
      id: '/api/public/connect-iq/v1/workout-events'
      path: '/api/public/connect-iq/v1/workout-events'
      fullPath: '/api/public/connect-iq/v1/workout-events'
      preLoaderRoute: typeof ApiPublicConnectIqV1WorkoutEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/connect-iq/v1/workouts/active': {
      id: '/api/public/connect-iq/v1/workouts/active'
      path: '/api/public/connect-iq/v1/workouts/active'
      fullPath: '/api/public/connect-iq/v1/workouts/active'
      preLoaderRoute: typeof ApiPublicConnectIqV1WorkoutsActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CoachRoute: CoachRoute,
  ConnectionsRoute: ConnectionsRoute,
  HistoryRoute: HistoryRoute,
  McpRoute: McpRoute,
  NutritionRoute: NutritionRoute,
  OnboardingRoute: OnboardingRoute,
  ProgramRoute: ProgramRoute,
  ProgressRoute: ProgressRoute,
  RecoveryRoute: RecoveryRoute,
  SettingsRoute: SettingsRoute,
  WorkoutRoute: WorkoutRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ExercisesExerciseIdRoute: ExercisesExerciseIdRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHealthConnectIngestRoute: ApiPublicHealthConnectIngestRoute,
  ApiPublicHealthConnectPairRoute: ApiPublicHealthConnectPairRoute,
  ApiPublicHealthConnectUnpairRoute: ApiPublicHealthConnectUnpairRoute,
  ApiPublicConnectIqV1PairRoute: ApiPublicConnectIqV1PairRoute,
  ApiPublicConnectIqV1UnpairRoute: ApiPublicConnectIqV1UnpairRoute,
  ApiPublicConnectIqV1WorkoutEventsRoute:
    ApiPublicConnectIqV1WorkoutEventsRoute,
  ApiPublicConnectIqV1WorkoutsActiveRoute:
    ApiPublicConnectIqV1WorkoutsActiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
